### ISSUE TITLE
Confusing license

### ISSUE THREAD

**Issue by JesusTheHun** [OAuth2-Framework/server-library#120]
Hello,

In the LICENSE file it's written : 

> The MIT License
> Copyright (c) 2014-2016 Florent Morselli

That's confusing, is this library under MIT license or is it under Copyright ?

**Comment by Spomky** [comment]
Unlike the GPL for example, the MIT licence is not copyleft but remains compatible with the GPL.
Its terms allow to indicate the licence holders by including the standard `Copyright (c) <year> <copyright holders>` line.

So, I may be wrong but I see no contradiction in that header.

**Comment by JesusTheHun** [comment]
Looks like I've misunderstood what a Copyright is. Crystal clear now :)
