### ISSUE TITLE
Write documentation

### ISSUE THREAD

**Issue by Spomky** [OAuth2-Framework/server-library#9]
The documentation of this library must be written
- [ ] Client and Client Manager
  - [ ] Token Endpoint Authentication Methods
- [ ] Endpoints
  - [ ] Authorization Endpoint
  - [ ] Token Endpoint
  - [ ] Client Registration Endpoint
  - [ ] Token Introspection Endpoint
  - [ ] Token Revocation Endpoint
- [x] Exception and Exception Manager
  - [x] Usage
  - [x] Custom Exceptions
  - [x] Extensions
- [x] Scope and Scope Manager
- [ ] User and User Account
- [ ] Grant Flows
  - [ ] Authorization Code
    - [ ] PKCE Methods
      - [ ] S256
      - [ ] Plain
  - [ ] Client Credentials
  - [ ] Implicit
  - [ ] JWT Bearer
  - [ ] Resource Owner Password Credentials
  - [ ] None
  - [ ] Refresh Token
- [x] Response Mode
  - [x] Query
  - [x] Fragment
  - [x] Form Post
- [ ] Tokens
  - [x] Access Token
  - [x] JWT Access Token
  - [ ] Refresh Token
- [x] Token Types
  - [x] Bearer
  - [x] MAC
  - [x] POP

**Comment by Raphy** [comment]
Hello, I would likle to test your library but.. I can't found any basic usage or an entry point of the library...

Maybe can you write a basic documentation that other developers can at least test the library and then contributing to improve the documentation ;)

**Comment by Spomky** [comment]
Hi,

You are right, I have to write a basic documentation to help other developers to test and use this library.
At the moment, I am writing more tests and fixing some bugs. When done, I will write the documentation.

**Comment by Raphy** [comment]
Thanks for the answer.

Well, I will wait until you release a documentation. Your library seems interesting, your implementation, at first sight, seduced me !

**Comment by Spomky** [comment]
https://github.com/OAuth2-Framework/OAuth2-Framework.github.io/issues/13
